Final Group Project/SpacePirateInventory/SpacePirateInventory/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpacePirateInventory.Data.Dapper;
using SpacePirateInventory.Data.DapperRepo;

namespace SpacePirateInventory.Controllers
{
    public class InventoryController : Controller
    {
        // GET: Inventory
        public ActionResult Index()
        {
            var repo = new CategoryRepository().GetAll();
            return View(repo);
        }

        public ActionResult Details(int id)
        {
            var repo = new PirateItemRepository().GetById(id);
            return View(repo);
        }

    }
}

Final Group Project/SpacePirateInventory/SpacePirateInventory/Controllers/UserController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using SpacePirateInventory.Data.DapperRepo;
using SpacePirateInventory.Models;
using SpacePirateInventory.Models.Queries;
using SpacePirateInventory.Models.Tables;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SpacePirateInventory.Controllers
{
    public class UserController : Controller
    {

        // GET: Admin
        [Authorize]
        public ActionResult Index()
        {

            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ViewBag.Name = user.Name;

                ViewBag.displayMenu = "No";

                if (IsAdminUser())
                {
                    ViewBag.displayMenu = "Yes";
                }
                return View();
            }
            else
            {
                ViewBag.Name = "Not Logged IN";
            }
            return View();
        }



        [Authorize]
        public ActionResult Article()
        {
            ViewBag.Message = "User article list.";

            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Add(Article model)
        {
            var repo = new ArticleRepository();
         
            var user = User.Identity;
            ViewBag.displayMenu = "Thanks";
            model.UserId = user.GetUserId();
                repo.AddArticle(model);
                return View();
          
        
         
        }

        [Authorize]
    
        public ActionResult Add()
        {
      
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ViewBag.Name = user.Name;

                ViewBag.displayMenu = "No";

                if (IsAdminUser())
                {
                    ViewBag.displayMenu = "Yes";
                }
          
                return View();
            }
            else
            {
                ViewBag.Name = "Not Logged IN";
            }

            return View();
        }
        public Boolean IsAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if ((s[0].ToString() == "Admin")|| s[0].ToString() == "User")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }
    }
}

Final Group Project/SpacePirateInventory/SpacePirateInventory/Views/Admin/AddItem.cshtml
@model SpacePirateInventory.Models.ItemAddViewModel
@{
    ViewBag.Title = "AddItem";
}
<div class="row">
    <div class="col-xs-12 col-md-6 col-lg-6">
        @Html.ActionLink("Back to Inventory List", "Inventory", "Admin")
        <h2 class="mt-5">Add Item</h2>
        @using (Html.BeginForm("Add", "Admin", FormMethod.Post, new { enctype = "multipart/form-data", id = "formAddItem" }))
    {
        @Html.ValidationSummary()
        <div>
            <div class="form-group">
                <label>Item Name</label>
                @Html.TextBoxFor(i => i.Item.ItemName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Category Name</label>
                @Html.DropDownListFor(i => i.Item.CategoryName, Model.Categories, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Real Value</label>
                @Html.TextBoxFor(i => i.Item.RealValue, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Value to display</label>
                @Html.TextBoxFor(i => i.Item.DisplayValue, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Description</label>
                @Html.TextAreaFor(i => i.Item.Description, new { @class = "form-control" })
            </div>
            <div class="form-check">
                @Html.CheckBoxFor(i => i.Item.Favorite, new { @class = "form-check-input" })
                <label class="form-check-label">Favorite</label>
            </div>
            <div class="form-check">
                @Html.CheckBoxFor(i => i.Item.Featured, new { @class = "form-check-input" })
                <label class="form-check-label">Featured</label>
            </div>
            <div class="form-group">
                <label>Currency</label>
                @Html.DropDownListFor(i => i.Item.CurrencyName, Model.Currencies, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Image</label>
                <input id="ImageUpload" name="ImageUpload" type="file" class="form-control" />
            </div>
        </div>
        <button class="btn btn-primary">Add Item</button>
}
    </div>
</div>


@section scripts{
    <script>
        $(document).ready(function () {
            $('#formAddItem').validate({
                rules: {
                    'Item.ItemName': {
                        required: true
                    },
                    'Item.RealValue': {
                        required: true,
                        number: true
                    },
                    'Item.DisplayValue': {
                        required: true,
                        number: true,
                        min: 1
                    },
                    'Item.Description': {
                        required: true
                    },
                    'Item.Favorite': {
                        required: true
                    },
                    'Item.Featured': {
                        required: true
                    },
                    'ImageUpload': {
                        required: true
                    }
                }
            });
        });

    </script>
}

Final Group Project/SpacePirateInventory/SpacePirateInventory/Views/Admin/Articles.cshtml
@model IEnumerable<SpacePirateInventory.Models.Queries.ArticleListItem>
@{
    ViewBag.Title = "Articles";
}

@if (ViewBag.displayMenu == "Yes")
{
    <div class="row">
        <div class="col-12">
            @Html.ActionLink("Add new Article", "Add", "User")
            <h1 class="mt-5">Article List</h1>
            <table class="table table-dark">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Approved</th>
                        <th>Edit|Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var article in Model)
            {
                <tr>
                    <td>@article.ArticleTitle</td>
                    <td>@article.UserName</td>
                    <td>@article.Approved</td>
                    <td>@Html.ActionLink("Edit", "EditArticle", "Admin", new { id = article.ArticleId }, null) | @Html.ActionLink("Delete", "DeleteArticle", "Admin", new { id = article.ArticleId }, null) </td>
                </tr>
    }
                </tbody>
            </table>
        </div>
    </div>

}
else
{
    <h2>  Welcome <strong>@ViewBag.Name</strong> :) . Please login to view this page! </h2>
}

Final Group Project/SpacePirateInventory/SpacePirateInventory/Views/Admin/EditArticle.cshtml
@model SpacePirateInventory.Models.ArticleEditViewModel
@{
    ViewBag.Title = "EditArticle";
}

<h2>EditArticle</h2>

@*@if (ViewBag.displayMenu == "Yes")
{*@
<div class="row mt-5">
    <div class="col-12">
        @Html.ActionLink("Back to Article List", "Articles", "Admin")
        <h1>Edit Article</h1>
        @using (Html.BeginForm("EditArticle", "Admin", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmEditArticle", @class= " col" }))
        {
            @Html.HiddenFor(i=>i.Article.ArticleId)
            @Html.ValidationSummary()
                <div class=" form-group">
                    <label>Title</label>
                    @Html.TextBoxFor(m => m.Article.ArticleTitle, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Author</label>
                    @Html.DropDownListFor(m => m.Article.UserId, Model.User, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Article Content</label>
                    @Html.TextAreaFor(m => m.Article.ArticleContent, new { @class = "form-control", rows = "5" })
                </div>
                <div class="form-check mb-3">
                    @Html.CheckBoxFor(i => i.Article.Approved, new { @class = "form-check-input" })
                    <label class="form-check-label">Approve</label>
                </div>
                <button class="btn btn-primary">Save</button> 
        }
    </div>
</div>
@*}
else
{
<h2>  Welcome <strong>@ViewBag.Name</strong> :) . Please login to view this page! </h2>
}*@

Final Group Project/SpacePirateInventory/SpacePirateInventory/Views/Admin/EditItem.cshtml
@model SpacePirateInventory.Models.ItemEditViewModel
@{
    ViewBag.Title = "EditItem";
}
<div class="row">
    <div class="col-xs-12 col-md-6 col-lg-6">
        @Html.ActionLink("Back to Inventory List", "Inventory", "Admin")
        <h2 class="mt-5">Edit Item</h2>
        @using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data", id = "formEditItem" }))
    {
        @Html.ValidationSummary()
        @Html.HiddenFor(i => i.Item.ItemId)
        <div>
            <div class="form-group">
                <label>Item Name</label>
                <br />
                @Html.TextBoxFor(i => i.Item.ItemName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Category Name</label>
                <br />
                @Html.DropDownListFor(i => i.Item.CategoryId, Model.Categories, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Real Value</label>
                <br />
                @Html.TextBoxFor(i => i.Item.RealValue, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Value to display</label>
                <br />
                @Html.TextBoxFor(i => i.Item.DisplayValue, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Description</label>
                <br />
                @Html.TextAreaFor(i => i.Item.Description, new { @class = "form-control" })
            </div>
            <div class="form-check">
                @Html.CheckBoxFor(i => i.Item.Favorite, new { @class = "form-check-input" })
                <label class="form-check-label">Favorite</label>
            </div>
            <div class="form-check">
                @Html.CheckBoxFor(i => i.Item.Featured, new { @class = "form-check-input" })
                <label class="form-check-label">Featured</label>
            </div>
            <div class="form-group">
                <label>Currency</label>
                <br />
                @Html.DropDownListFor(i => i.Item.CurrencyId, Model.Currencies, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <img src="@Url.Content("~/Images/" + Model.Item.ItemPictureURL)" />
                <label>Image</label>
                <input id="ImageUpload" name="ImageUpload" type="file" class="form-control" />
            </div>
        </div>
        <button class="btn btn-primary">Edit Item</button>
}
    </div>
</div>


@section scripts{
    <script>
        $(document).ready(function () {
            $('#formEditItem').validate({
                rules: {
                    'Item.ItemName': {
                        required: true
                    },
                    'Item.RealValue': {
                        required: true,
                        number: true
                    },
                    'Item.DisplayValue': {
                        required: true,
                        number: true,
                        min: 1
                    },
                    'Item.Description': {
                        required: true
                    },
                    'Item.Favorite': {
                        required: true
                    },
                    'Item.Featured': {
                        required: true
                    }
                }
            });
        });

    </script>
}

Final Group Project/SpacePirateInventory/SpacePirateInventory/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@if (ViewBag.displayMenu == "Yes")
{

    <div class="row mt-5">
        <div class="col-6">
            <ul class="list-group">
                @Html.ActionLink("View Inventory", "Inventory", "Admin", null, new { @class = "list-group-item" })
                @Html.ActionLink("View Users", "Users", "Admin", null, new { @class = "list-group-item" })
                @Html.ActionLink("View Articles", "Articles", "Admin", null, new { @class = "list-group-item" })
            </ul>
                
        </div>
    </div>

}
else
{
    <h2>  Welcome <strong>@ViewBag.Name</strong> :) . Please login to view this page! </h2>
}

Final Group Project/SpacePirateInventory/SpacePirateInventory/Views/Admin/Inventory.cshtml
@model IEnumerable<SpacePirateInventory.Models.Queries.ItemLong>
@{
    ViewBag.Title = "Inventory";
}

@if (ViewBag.displayMenu == "Yes")
{

    <div class="row mt-5">
        <div class="col-12">
            <h1>Inventory List</h1>
            @Html.ActionLink("Add New Item", "AddItem", "Admin")
            <table class="table table-dark mt-3">
                <thead>
                    <tr>
                        <th>Item #</th>
                        <th>Item Name</th>
                        <th>Category</th>
                        <th>Actual Value</th>
                        <th>Display Value</th>
                        <th>Currency</th>
                        <th>Edit|Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.ItemId</td>
                            <td>@item.ItemName</td>
                            <td>@item.CategoryName</td>
                            <td>$@item.RealValue</td>
                            <td>$@item.DisplayValue</td>
                            <td>@item.CurrencyName</td>
                            <td>@Html.ActionLink("Edit", "EditItem", "Admin", new { id = item.ItemId }, null) | 
                            @Html.ActionLink("Delete", "DeleteItem", "Admin", new { id = item.ItemId }, null) 
                            
                            @*@using (Html.BeginForm("DeleteItem", "Admin", FormMethod.Post))
                            {
                                @Html.Hidden("ItemId", item.ItemId)
                                <buttn class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item!');">Delete</buttn>
                            }*@
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

}
else
{
    <h2>  Welcome <strong>@ViewBag.Name</strong> :) . Please login to view this page! </h2>
}

Final Group Project/SpacePirateInventory/SpacePirateInventory/Views/Admin/Users.cshtml
@model IEnumerable<SpacePirateInventory.Models.Queries.UserListItem>
@{
    ViewBag.Title = "Users";
}

@if (ViewBag.displayMenu == "Yes")
{
    <div class="row mt-5">
        <div class="col-12">
            <h1>User List</h1>
            <table class="table table-dark">
                <thead>
                    <tr>
                        <th>User Name</th>
                        <th>Role</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model)
                    {
                        <tr>
                            <td>@user.UserName</td>
                            <td>@user.Name</td>
                            <td>@user.Email</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

}
else
{
    <h2>  Welcome <strong>@ViewBag.Name</strong> :) . Please login to view this page! </h2>
}