Final Project/Card Dealership/Spark/Spark.UI/Controllers/CardInfoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Spark.Data.Factory;
using Spark.Models.Tables;
using Spark.UI.Models;

namespace Spark.UI.Controllers
{
    public class CardInfoController : Controller
    {
        // GET: CardInfo
        public ActionResult Details(int id)
        {
            var repo = CardInfoRepositoryFactory.GetRepository();
            var model = repo.GetDetails(id);

            return View(model);
        }

        public ActionResult Index()
        {
            var repo = SetsRepositoryFactory.GetRepository();
            
            return View(repo.GetAll());
        }

        public ActionResult Add()
        {
            var model = new CardInfoAddViewModel();

            var setsRepo = SetsRepositoryFactory.GetRepository();
            var artistsRepo = ArtistRepositoryFactory.GetRepository();

            model.Sets = new SelectList(setsRepo.GetAll(), "SetId", "SetName");
            model.Artists = new SelectList(artistsRepo.GetAll(), "ArtistId", "ArtistName");
            model.CardInfo = new CardInfo();
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Add(CardInfoAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                var repo = CardInfoRepositoryFactory.GetRepository();

                try
                {
                    var savepath = Server.MapPath("~/Images");

                    string fileName = Path.GetFileNameWithoutExtension(model.ImageUpload.FileName);
                    string extension = Path.GetExtension(model.ImageUpload.FileName);

                    var filePath = Path.Combine(savepath, fileName + extension);

                    int counter = 1;
                    while (System.IO.File.Exists(filePath))
                    {
                        filePath = Path.Combine(savepath, fileName + counter.ToString() + extension);
                        counter++;
                    }

                    model.ImageUpload.SaveAs(filePath);

                    model.CardInfo.CardArtURL = Path.GetFileName(filePath);

                    repo.Insert(model.CardInfo);

                    return RedirectToAction("Edit", new { id = model.CardInfo.CardId });
                }
                catch(Exception ex)
                {
                    throw ex;
                }
            }
            else
            {
                var setsRepo = SetsRepositoryFactory.GetRepository();
                model.Sets = new SelectList(setsRepo.GetAll(), "SetId", "SetName");
                var artistsRepo = ArtistRepositoryFactory.GetRepository();
                model.Artists = new SelectList(artistsRepo.GetAll(), "ArtistId", "ArtistName");
                return View(model);
            }
             
        }

        public ActionResult Edit(int id)
        {
            var model = new CardInfoEditViewModel();

            var setsRepo = SetsRepositoryFactory.GetRepository();
            var artistsRepo = ArtistRepositoryFactory.GetRepository();
            var cardInfoRepo = CardInfoRepositoryFactory.GetRepository();

            model.Sets = new SelectList(setsRepo.GetAll(), "SetId", "SetName");
            model.Artists = new SelectList(artistsRepo.GetAll(), "ArtistId", "ArtistName");
            model.CardInfo = cardInfoRepo.GetById(id);

            //if(user is not admin)
            //{
            //   throw new Exception("Only the admin can edit");
            //}

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(CardInfoEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var repo = CardInfoRepositoryFactory.GetRepository();
                var oldCardInfo = repo.GetById(model.CardInfo.CardId);
                try
                {
                    if (oldCardInfo.CardArtURL != model.ImageUpload.FileName)
                    {
                        var savepath = Server.MapPath("~/Images");

                        string fileName = Path.GetFileNameWithoutExtension(model.ImageUpload.FileName);
                        string extension = Path.GetExtension(model.ImageUpload.FileName);

                        var filePath = Path.Combine(savepath, fileName + extension);

                        int counter = 1;
                        while (System.IO.File.Exists(filePath))
                        {
                            filePath = Path.Combine(savepath, fileName + counter.ToString() + extension);
                            counter++;
                        }
                        model.ImageUpload.SaveAs(filePath);
                        model.CardInfo.CardArtURL = Path.GetFileName(filePath);

                        var oldPath = Path.Combine(savepath, oldCardInfo.CardArtURL);
                        if (System.IO.File.Exists(oldPath))
                        {
                            System.IO.File.Delete(oldPath);
                        }
                    }
                    repo.Update(model.CardInfo);

                    return RedirectToAction("Edit", new { id = model.CardInfo.CardId });
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            else
            {
                var setsRepo = SetsRepositoryFactory.GetRepository();
                model.Sets = new SelectList(setsRepo.GetAll(), "SetId", "SetName");
                var artistsRepo = ArtistRepositoryFactory.GetRepository();
                model.Artists = new SelectList(artistsRepo.GetAll(), "ArtistId", "ArtistName");
                return View(model);
            }

        }
    }
}

Final Project/Card Dealership/Spark/Spark.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Spark.Data.Factory;

namespace Spark.UI.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            var model = CardInfoRepositoryFactory.GetRepository().GetMostExpensive();
            return View(model);
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Final Project/Card Dealership/Spark/Spark.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<style>
    #map {
        height: 400px;
        width: 100%;
    }
</style>


<h3>Contact Us</h3>


<div class="row">

    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="form-group">
            <label><strong>Name</strong></label>
            <br />
            <input type="text" name="Name" placeholder="Full name" />
        </div>
        <div class="form-group">
            <label><strong>Email</strong></label>
            <br />
            <input type="email" name="Email" placeholder="example@gmail.com" />
        </div>
        <div class="form-group">
            <label><strong>Phone</strong></label>
            <br />
            <input type="tel" name="Phone" placeholder="111-111-1111" />
        </div>
        <div class="form-group">
            <label><strong>Message</strong></label>
            <br />
            <textarea rows="4" cols="50" name="Message" form="usrform" /></textarea>
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-6">
        <div id="map"></div>
        <script>
            function initMap() {
                var uluru = { lat: 36.2048, lng: 138.2529 };
                var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 4,
                    center: uluru
                });
                var marker = new google.maps.Marker({
                    position: uluru,
                    map: map
                });
            }
        </script>

        <address>
            One Microsoft Way<br />
            Redmond, WA 98052-6399<br />
            <abbr title="Phone">P:</abbr>
            425.555.0100
        </address>

        <address>
            <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
            <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
        </address>
    </div>

</div>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBR7gDX0a7zB8upeaxlNyd2H3ZwuyGrpYw&callback=initMap">
</script>

Final Project/Card Dealership/Spark/Spark.UI/Views/Home/Index.cshtml
@model IEnumerable<Spark.Models.Queries.CardShortItem>
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Light that spark!</h1>
    <p class="lead">We have some cards that you should buy! Look at 'em!</p>
</div>

<div class="row">
    <div class="col-xs-12">
        <h2>Featured Cards</h2>
    </div>
</div>
<div class="row">
    @*<div class="col-xs-12">*@
        @foreach (var card in Model)
        {
            <a href="../CardInfo/Details/@card.CardId">
            <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="card text-center">

                    <img style="height: 460px; width: 100%;" src="@Url.Content("~/Images/" + card.CardArtURL)" />
                    <h5 class="card-title">@card.CardName</h5>
                    <p>#@card.CardNumber, @card.SetName, @card.MSRP.ToString("c")</p>
                    <p>@Html.ActionLink("view card", "Details", "CardInfo",new { id = card.CardId }, null)</p>
                </div>
            </div>
                </a>
        }
    @*</div>*@
</div>